config/routes.rb
Lits::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  root 'home#index'

  match 'about' => 'home#about', :via => :get
  match 'blog' => 'posts#index', :via => :get
  match 'process_contacts' => 'home#process_contacts', :via => :post

  get 'works' => 'work#index'

  get '404', :to => 'errors#not_found'

  get 'works/vgonke' => 'work#index'
  get 'works/crackers' => 'work#index'
  get 'works/frenzy' => 'work#index'

  get 'services' => 'services#index'

  get 'admin' => 'admin#index'

  get 'video_chat' => 'demo#video_chat'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :posts, :only => [:index]

  resources :vacancies, :only => [:index, :show]

  resources :replies, only: [:new, :create]

  get '/contact' => 'application#contact'

  get 'career' => 'career#index'

  namespace :admin do
    resources :users
    resources :services
    resources :posts
    resources :pages
    resources :vacancies do
      member do
        get 'clone'
        get 'toggle_freeze'
      end
    end
    resources :replies, only: [:index, :delete]
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = Service.all.order("updated_at desc")
  end

  def show
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :title, :header, :body, :image_url, :big_image_url, :display_mode)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all.order("updated_at desc")
    parse_page_meta_info "services"
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.haml
= form_for([:admin, @service]) do |f|
  - if @service.errors.any?
    #error_explanation
      %h2
        = pluralize(@service.errors.count, "error")
        prohibited this service from being saved:
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name, :size => 100
  .field
    = f.label :title
    %br/
    = f.text_field :title, :size => 100
  .field
    = f.label :header
    %br/
    = f.text_area :header, :size => "100x3"
  .field
    = f.label :body
    %br/
    = f.text_area :body, :size => "100x20"
  .field
    = f.label :image_url
    %br/
    = f.text_field :image_url, :size => 100
  .field
    = f.label :big_image_url
    %br/
    = f.text_field :big_image_url, :size => 100
  .field
    = f.label :display_mode
    %br/
    = f.text_field :display_mode, :size => 100
  .actions
    = f.submit

app/views/admin/services/edit.html.haml
%h1 Editing service
= render 'form'
= link_to 'Show', [:admin, @service]
|
\#{link_to 'Back', admin_services_path}

app/views/admin/services/index.html.haml
%h1 Listing services
= link_to 'Create new service', new_admin_service_path
%br/
%br/
- @services.each do |service|
  %div
    .icon-wrap
      %img{:src => service.image_url}/
    %h3= service.title
    %p= service.header
  = link_to 'Show', [:admin, service]
  |
  \#{link_to 'Edit', edit_admin_service_path(service)} |
  \#{link_to 'Destroy', [:admin, service], method: :delete, data: { confirm: 'Are you sure?' }}

app/views/admin/services/new.html.haml
%h1 New service
= render 'form'
= link_to 'Back', admin_services_path

app/views/admin/services/show.html.haml
%p#notice= notice
.container
  .two.columns
    .post-img
      %img.img-border.img_wrap1{:alt => "", :src => @service.big_image_url}/
  .fourteen.columns.portfolio-content
    %h2.headline
      = @service.title
    %p
      = @service.header.html_safe
    = @service.body.html_safe
= link_to 'Edit', edit_admin_service_path(@service)
|
\#{link_to 'Back', admin_services_path}