config/routes.rb
Lits::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  root 'home#index'

  match 'about' => 'home#about', :via => :get
  match 'blog' => 'posts#index', :via => :get
  match 'process_contacts' => 'home#process_contacts', :via => :post

  get 'works' => 'work#index'

  get '404', :to => 'errors#not_found'

  get 'works/vgonke' => 'work#index'
  get 'works/crackers' => 'work#index'
  get 'works/frenzy' => 'work#index'

  get 'services' => 'services#index'

  get 'admin' => 'admin#index'

  get 'video_chat' => 'demo#video_chat'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :posts, :only => [:index]

  resources :vacancies, :only => [:index, :show]

  resources :replies, only: [:new, :create]

  get '/contact' => 'application#contact'

  get 'career' => 'career#index'

  namespace :admin do
    resources :users
    resources :services
    resources :posts
    resources :pages
    resources :vacancies do
      member do
        get 'clone'
        get 'toggle_freeze'
      end
    end
    resources :replies, only: [:index, :delete]
  end
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  after_create ->(created_vacancy) do
    CareerMailer.vacancy_created(created_vacancy).deliver
  end

  STATUSES = [:actual, :frozen]

  has_many :replies
  belongs_to :user

  scope :owned_by, ->(user) { where(user_id: user.id) }

  validates :name, :description, presence: true
  validates :name, length: { minimum: 2, maximum: 128 }
  validates :description, length: { minimum: 1, maximum: 4096 }

  def status
    STATUSES[super]
  end

  def status= value
    super STATUSES.map.with_index.to_h[value]
  end

  STATUSES.each { |status| define_method("#{status}?") { self.status == status } }
end

app/controllers/admin/vacancies_controller.rb
class Admin::VacanciesController < AdminController
  before_action :set_vacancy, only: [:edit, :update, :clone, :toggle_freeze, :destroy]

  def index
    @vacancies = current_user.is_admin? ? Vacancy.all : Vacancy.owned_by(current_user)
    @vacancies = @vacancies.owned_by(User.find(params[:user_filter])) if params[:user_filter].present?
  end

  def clone
    copy = @vacancy.dup
    if copy.save
      flash[:notice] = I18n.t 'vacancies.clone.success'
    else
      flash[:error] = I18n.t 'vacancies.clone.fail'
    end

    redirect_to action: :index
  end

  def toggle_freeze
    new_status = @vacancy.frozen? ? :actual : :frozen
    if @vacancy.update_attribute :status, new_status
      flash[:notice] = I18n.t "vacancies.toggle_freeze.#{ new_status == :frozen ? 'freeze' : 'unfreeze' }.success"
    else
      flash[:error] = I18n.t "vacancies.toggle_freeze.#{ new_status == :frozen ? 'freeze' : 'unfreeze' }.fail"
    end

    redirect_to action: :index
  end

  def new
    @vacancy = Vacancy.new vacancy_params
  end

  def create
    @vacancy = Vacancy.new vacancy_params
    if @vacancy.valid?
      if @vacancy.save
        flash[:notice] = I18n.t 'vacancies.create.success'
        redirect_to action: :index
      else
        flash[:error] = I18n.t 'vacancies.create.fail'
        redirect_to action: :new
      end
    else
      flash[:error] = humanized_validation_error_message(@vacancy)
      redirect_to action: :new, vacancy: vacancy_params
    end
  end

  def edit
  end

  def update
    if @vacancy.update vacancy_params
      flash[:notice] = I18n.t 'vacancies.update.success'
    else
      flash[:error] = I18n.t 'vacancies.update.fail'
    end
    redirect_to action: :index
  end

  def destroy
    if @vacancy.destroy
      flash[:notice] = I18n.t 'vacancies.destroy.success'
    else
      flash[:error] = I18n.t 'vacancies.destroy.fail'
    end
    redirect_to action: :index
  end

  private

  def vacancy_params
    params[:vacancy].present? ? params.require(:vacancy).permit(:name, :description, :salary, :user_id) : nil
  end

  def set_vacancy
    @vacancy = Vacancy.find params[:id]
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:reply, :apply]

  def index
    @vacancies = Vacancy.all
  end

  private

  def set_vacancy
    @vacancy = Vacancy.find params[:id]
  end

end

app/helpers/vacancies_helper.rb
module VacanciesHelper
  def select_options_owner
    (User.hrs + User.admins).map { |user| [user.name, user.id] }
  end

  def select_options_spoken_english
    options = {}
    (I18n.t 'vacancies.reply.english.spoken_levels').each do |key, value|
      options[value] = key if (0..Reply::SPOKEN_ENGLISH_LEVELS - 1).include? key.to_i
    end
    options_for_select options, 1
  end

  def select_options_user_filter
    options = [['All', 0]] + (User.hrs + User.admins).map { |user| [user.name, user.id] }
    options_for_select options, params[:user_filter].present? ? params[:user_filter] : options[0][0]
  end

  def contact_type_icon type
    {
      'phone' => 'phone',
      'email' => 'envelope',
      'skype' => 'skype'
    }[type]
  end
end

app/views/admin/vacancies/_form.html.haml
= form_for([:admin, @vacancy]) do |f|
  .input-cell
    = f.label :name
    = f.text_field :name
  .input-cell
    = f.label :description, class: 'description'
    = f.text_area :description
  .input-cell
    = f.label :salary
    = f.text_field :salary
  - if current_user.is_admin?
    .input-cell
      = f.label :user_id, 'Owner'
      = f.select :user_id, select_options_owner
  - else
    = f.hidden_field :user_id, value: current_user.id
  = f.submit t(action_name == 'new' ? 'vacancies.new.submit' : 'vacancies.edit.submit')

app/views/admin/vacancies/_vacancy.html.haml
.vacancy
  .actions-panel
    .action.replies{ title: t('vacancies.vacancy.actions.replies') }
      = link_to admin_replies_path(vacancy_id: vacancy.id) do
        = fa_icon 'reply-all'
    .action.edit{ title: t('vacancies.vacancy.actions.edit') }
      = link_to edit_admin_vacancy_path(vacancy) do
        = fa_icon 'pencil'
    .action.clone{ title: t('vacancies.vacancy.actions.clone') }
      = link_to clone_admin_vacancy_path(vacancy) do
        = fa_icon 'copy'
    .action.clone{ title: vacancy.frozen? ? t('vacancies.vacancy.actions.unfreeze') : t('vacancies.vacancy.actions.freeze') }
      = link_to toggle_freeze_admin_vacancy_path(vacancy) do
        = fa_icon 'clock-o'
    .action.delete{ title: t('vacancies.vacancy.actions.delete') }
      = link_to(admin_vacancy_path(vacancy), method: :delete) do
        = fa_icon 'trash'
  .vacancy-content
    .head
      = fa_icon 'clock-o' if vacancy.frozen?
      .name{ title: t('vacancies.vacancy.titles.name') }
        = vacancy.name
      .salary{ title: t('vacancies.vacancy.titles.salary') }
        %div
          = fa_icon 'money'
          %div
            = vacancy.salary || t('vacancies.vacancy.salary.none')
      .owner{ title: t('vacancies.vacancy.titles.owner') }
        %div
          = fa_icon 'user'
          %div
            = vacancy.user.present? ? vacancy.user.name : t('vacancies.vacancy.user.none')
    .details{ title: t('vacancies.vacancy.titles.details') }
      = vacancy.description.html_safe

app/views/admin/vacancies/edit.html.haml
.edit-vacancy
  = render 'form'

app/views/admin/vacancies/index.html.haml
.vacancies
  .control-panel
    .control-panel-cell.add-button
      = link_to new_admin_vacancy_path do
        = fa_icon 'plus'
    - if current_user.is_admin?
      .control-panel-cell.filter-area
        = t 'vacancies.index.filter'
        = select_tag :user_filter, select_options_user_filter

  .vacancy-list
    - if @vacancies.try(:any?)
      = render @vacancies
    - else
      .empty-result
        = t 'vacancies.index.empty-result'

= javascript_include_tag 'vacancy'
= javascript_include_tag 'vacanciesViewer'

app/views/admin/vacancies/new.html.haml
.new-vacancy
  = form_for(:vacancy, { url: admin_vacancies_url, method: :post }) do |f|
    .input-cell
      = f.label :name
      = f.text_field :name
    .input-cell
      = f.label :description, class: 'description'
      = f.text_area :description
    .input-cell
      = f.label :salary
      = f.text_field :salary
    - if current_user.is_admin?
      .input-cell
        = f.label :user_id, 'Owner'
        = f.select :user_id, select_options_owner
    = f.submit t('vacancies.new.submit')