config/routes.rb
Lits::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts

  root 'home#index'

  match 'about' => 'home#about', :via => :get
  match 'blog' => 'posts#index', :via => :get
  match 'process_contacts' => 'home#process_contacts', :via => :post

  get 'works' => 'work#index'

  get '404', :to => 'errors#not_found'

  get 'works/vgonke' => 'work#index'
  get 'works/crackers' => 'work#index'
  get 'works/frenzy' => 'work#index'

  get 'services' => 'services#index'

  get 'admin' => 'admin#index'

  get 'video_chat' => 'demo#video_chat'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :posts, :only => [:index]

  resources :vacancies, :only => [:index, :show]

  resources :replies, only: [:new, :create]

  get '/contact' => 'application#contact'

  get 'career' => 'career#index'

  namespace :admin do
    resources :users
    resources :services
    resources :posts
    resources :pages
    resources :vacancies do
      member do
        get 'clone'
        get 'toggle_freeze'
      end
    end
    resources :replies, only: [:index, :delete]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vacancies
  has_secure_password

  ROLES = [:customer, :hr, :admin]

  ROLES.each do |role|
    scope role.to_s + 's', ->() do
      role_i = 0
      loop do
        break if ROLES[role_i] == role
        role_i++
      end
      where(role: role_i)
    end
  end

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, email: true
  validates :role, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: ROLES.size - 1 }

  ROLES.each { |role_name| define_method("is_#{ role_name }?") { ROLES[self.role] == role_name } }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: "User #{@user.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for([:admin, @user]) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :password
    %br/
    = f.password_field :password
  %div
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/admin/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', [:admin, @user]
|
\#{link_to 'Back', admin_users_path}

app/views/admin/users/index.html.haml
%h1 Users
= link_to 'Create new user', new_admin_user_path
%br/
%br/
- @users.each do |user|
  %h2= user.name
  = link_to 'Edit', edit_admin_user_path(user)
  |
  \#{link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }}

app/views/admin/users/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', admin_users_path

app/views/admin/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
= link_to 'Edit', edit_admin_user_path(@user)
|
\#{link_to 'Back', admin_users_path}